import '../styles/index.css';

export const metadata = {
  title: "Pizza's Next.js App",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className="min-h-screen w-full bg-primary-black overflow-hidden flex flex-col items-center">
        {children}
      </body>
    </html>
  );
}
